OPENAI_API_KEY = "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"
PINECONE_API_KEY = "pcsk_7GLZih_9N5zJucrPbJdidh6iE2JV7qkNfXS2Pg9F9bBUx7JvLrwwVUTfZmBfF5p86fGxd4"
PINECONE_ENVIRONMENT = "us-west-2"